export {};

declare global {
  interface Env {
    // Existing bindings are generated by `wrangler types` into `worker-configuration.d.ts`.
    // This file augments that interface with additional vars/secrets used by the app.

    // Turnstile (email/password auth endpoints).
    TURNSTILE_ENABLED?: string;
    TURNSTILE_SECRET_KEY?: string;

    // Google sign-in (audience check).
    GOOGLE_CLIENT_ID?: string;

    // Email verification (Resend).
    RESEND_API_KEY?: string;
    EMAIL_FROM?: string;
    APP_BASE_URL?: string;

    // Admin maintenance (manual, on-demand).
    // Keep this secret and only set it in environments where you want this endpoint enabled.
    ADMIN_PURGE_KEY?: string;
  }
}

